parameters:
    bitbag.shipping_gateway.validation_groups: ['bitbag']
    bitbag.shipping_labels_path: '%kernel.root_dir%/../shipping_labels'

imports:
    - { resource: services/event_listener.yml }
    - { resource: services/form.yml }
    - { resource: services/component.yml }
    - { resource: services/calculator.yml }

